[tool.poetry]
name = "reworkd_platform"
version = "0.1.0"
description = ""
authors = [

]
maintainers = [

]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.89.1"
uvicorn = { version = "^0.20.0", extras = ["standard"] }
pydantic = { version = "^1.10.4", extras = ["dotenv"] }
yarl = "^1.8.2"
ujson = "^5.7.0"
SQLAlchemy = { version = "^2.0.0", extras = ["asyncio"] }
aiomysql = "^0.1.1"
mysqlclient = "^2.1.1"
httptools = "^0.5.0"
sentry-sdk = "^1.14.0"
loguru = "^0.6.0"
aiokafka = "^0.8.0"
requests = "^2.29.0"
langchain = "^0.0.162"
openai = "^0.27.6"
wikipedia = "^1.4.0"


[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
flake8 = "~4.0.1"
mypy = "^1.1.1"
isort = "^5.11.4"
pre-commit = "^3.0.1"
wemake-python-styleguide = "^0.17.0"
black = "^22.12.0"
autoflake = "^1.6.1"
pytest-cov = "^4.0.0"
anyio = "^3.6.2"
pytest-env = "^0.8.1"
httpx = "^0.23.3"
taskiq = { version = "^0", extras = ["reload"] }

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["reworkd_platform", ]

[tool.mypy]
strict = true
ignore_missing_imports = true
allow_subclassing_any = true
allow_untyped_calls = true
pretty = true
show_error_codes = true
implicit_reexport = true
allow_untyped_decorators = true
warn_unused_ignores = false
warn_return_any = false
namespace_packages = true

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore:.*unclosed.*:ResourceWarning",
]
env = [
    "REWORKD_PLATFORM_ENVIRONMENT=pytest",
    "REWORKD_PLATFORM_DB_BASE=reworkd_platform_test",
    "REWORKD_PLATFORM_SENTRY_DSN=",
]

[fastapi-template.options]
project_name = "reworkd_platform"
api_type = "rest"
enable_redis = "None"
enable_rmq = "None"
ci_type = "github"
enable_migrations = "None"
enable_taskiq = "None"
enable_kube = "None"
kube_name = "reworkd-platform"
enable_routers = "None"
enable_kafka = "True"
enable_loguru = "True"
traefik_labels = "None"
add_dummy = "None"
orm = "sqlalchemy"
self_hosted_swagger = "None"
prometheus_enabled = "None"
sentry_enabled = "True"
otlp_enabled = "None"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
